CREATE TABLE IF NOT EXISTS blocks (
    difficulty DECIMAL(38,0),
    extra_data STRING,
    gas_limit BIGINT,
    gas_used BIGINT,
    hash STRING,
    logs_bloom STRING,
    miner STRING,
    mix_hash STRING,
    nonce STRING,
    number BIGINT,
    parent_hash STRING,
    receipts_root STRING,
    sha3_uncles STRING,
    size BIGINT,
    state_root STRING,
    timestamp BIGINT,
    total_difficulty DECIMAL(38,0),
    transaction_count BIGINT,
    transactions_root STRING
)
